# Generated by Django 5.0.4 on 2024-05-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.TextField(blank=True, null=True)),
                ('host', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('label', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('ip', models.TextField(max_length=50)),
                ('model', models.TextField(max_length=50)),
                ('location', models.TextField(max_length=50)),
                ('last_log', models.TextField(max_length=50)),
                ('ping', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
