# Generated by Django 5.1.1 on 2024-10-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Site', max_length=200)),
                ('maintenance_mode', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('contact_email', models.EmailField(default='admin@example.com', max_length=254)),
                ('items_per_page', models.IntegerField(default=20)),
                ('ping_retries', models.IntegerField(default=5)),
                ('notifications_mode', models.IntegerField(choices=[(0, 'None'), (1, 'System down'), (2, 'Log anomaly'), (3, 'Both')], default=0)),
                ('email_host', models.CharField(default='smtp.example.com', max_length=200)),
                ('email_port', models.IntegerField(default=465)),
                ('email_host_user', models.CharField(default='from@example.com', max_length=200)),
                ('email_host_password', models.CharField(default='password', max_length=200)),
                ('email_use_ssl', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('email_from_address', models.EmailField(default='noreply@example.com', max_length=254)),
                ('on_model_change_reset_labels', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('ml_model', models.IntegerField(choices=[(0, 'K-Means'), (1, 'AHC'), (2, 'SOM')], default=0)),
                ('ml_clusters', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=2)),
                ('ml_train', models.IntegerField(default=10000)),
                ('ml_classify', models.IntegerField(default=2000)),
                ('last_changed_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
